name: staging 브랜치

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches:
      - staging

jobs:
  push-to-fork:
    runs-on: ubuntu-latest
    container: pandoc/latex
    steps:
      - uses: actions/checkout@v4
      - name: Install mustache (to update the date)
        run: apk add ruby && gem install mustache
      - name: creates output
        run: sh ./build.sh
      - name: Pushes to another repository
        id: push_directory
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.AUTO_ACTIONS }}
        with:
          source-directory: 'output'
          destination-github-username: 'window-ook'
          destination-repository-name: 'meet2-web'
          user-email: ${{ secrets.EMAIL }}
          commit-message: ${{ github.event.commits[0].message }}
          target-branch: staging
      - name: Test get variable exported by push-to-another-repository
        run: echo $DESTINATION_CLONED_DIRECTORY

  Deploy-Preview:
    runs-on: ubuntu-latest
    needs: push-to-fork
    steps:
      - name: Github Repository 파일 가져오기
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # PNPM 설치 단계 추가
      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 10.11
          run_install: false

      # pnpm 저장소 캐시 설정
      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: 의존성(라이브러리) 설치
        run: pnpm install

      - name: Run Tests
        run: pnpm test

      - name: Vercel CLI 설치
        run: pnpm install --global vercel@latest

      - name: Vercel 환경 정보 가져오기
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      - name: 프로젝트 빌드
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

      - name: Vercel에 프로젝트 배포
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
